#!/bin/bash
#Please set these paths according to your system!
#
export BLAS_LIB_DIR="/home/userid/lib" #Path to BLAS library
export LAPACK_LIB_DIR="/home/userid/lib" #Path to LAPACK library
export NLOPT_LIB_DIR="/home/userid/lib/nlopt/lib" #Path to NLopt
export NLOPT_INCLUDE_DIR="/home/userid/lib/nlopt/include"
export MATH_LIB_NAMES="blas;lapack;lapack;blas;gfortranbegin;gfortran" #Change if your BLAS library is not libblas.a or if your LAPACK library is not liblapack.a. gfortranbegin/gfortran needed for GCC gfortran.
#export MPI_INCLUDE_PATH="/usr/include" #might not be necessary if CXX set correctly
#export MPI_LIBRARY="/usr/lib" #might not be necessary if CXX set correctly
export CXX="/usr/bin/mpicxx.mpich2" #Set this if using MPI

